"""Bake a bitmap font into the shim.

Rendering text through the browser was the first thing tried and it is the wrong
answer here: the result would differ between browsers and between a native build
and WebAssembly, and this port is worth being able to compare against itself.
The sizes needed are also bounded - the port's font cache holds ten heights and
clamps to a minimum of nine pixels - so there is nothing to gain from a scalable
face at run time.

So the glyphs are rasterised once, here, and committed as data.  DejaVu Sans is
the source: it is a Bitstream Vera derivative whose licence permits
redistribution, and it ships with matplotlib so no download is needed.  The game
asks GDI for Arial; DejaVu is a different face with different metrics, which is
a visible difference from the original and is recorded as such in the README.

One bit per pixel, packed rows, MSB first.  Output is a C++ header.
"""

import argparse
import os
import sys

from PIL import Image, ImageDraw, ImageFont

# The port's cache holds ten heights from nine pixels up, and the chrome asks
# for thirteen.  Anything else picks the nearest of these.
SIZES = [9, 10, 11, 12, 13, 14, 16, 18, 20, 24]

FIRST = 0x20
LAST = 0x7E


def render(path, size):
    """One size: (advance, width, height, top, rows) per glyph."""
    font = ImageFont.truetype(path, size)
    ascent, descent = font.getmetrics()
    glyphs = []
    for code in range(FIRST, LAST + 1):
        ch = chr(code)
        advance = int(round(font.getlength(ch)))

        # Draw into a box tall enough for the whole face, then trim, so a
        # glyph's vertical position is recorded rather than guessed at.
        box = Image.new("L", (size * 3 + 4, ascent + descent + 4), 0)
        draw = ImageDraw.Draw(box)
        # fontmode "1" asks for the rasteriser's own one-bit output rather than
        # an antialiased image to threshold afterwards.  At nine pixels the
        # difference is not cosmetic: thresholding loses the stem of a 1 and the
        # bar of a $, so the two most important glyphs in the game's status line
        # come out as something else entirely.
        draw.fontmode = "1"
        draw.text((2, 2), ch, font=font, fill=255)
        bbox = box.getbbox()

        if bbox is None:                      # space and friends
            glyphs.append((advance, 0, 0, 0, []))
            continue

        left, top, right, bottom = bbox
        w, h = right - left, bottom - top
        crop = box.crop(bbox)

        rows = []
        stride = (w + 7) // 8
        pixels = crop.load()
        for y in range(h):
            row = bytearray(stride)
            for x in range(w):
                # Already one bit; anything not zero is ink.
                if pixels[x, y]:
                    row[x // 8] |= 0x80 >> (x % 8)
            rows.append(bytes(row))

        glyphs.append((advance, w, h, top - 2, rows))
    return ascent, descent, glyphs


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("font")
    parser.add_argument("output")
    args = parser.parse_args()

    if not os.path.exists(args.font):
        sys.exit("no such font: %s" % args.font)

    blob = bytearray()
    faces = []
    for size in SIZES:
        ascent, descent, glyphs = render(args.font, size)
        entries = []
        for advance, w, h, top, rows in glyphs:
            offset = len(blob)
            for row in rows:
                blob += row
            entries.append((advance, w, h, top, offset))
        faces.append((size, ascent, descent, entries))

    lines = []
    lines.append("// Generated by tools/make_font.py - do not edit.")
    lines.append("//")
    lines.append("// DejaVu Sans, rasterised at the sizes the port asks for, one")
    lines.append("// bit per pixel with packed rows, MSB first.  See")
    lines.append("// THIRD_PARTY_LICENSES/dejavu.md for the font's licence.")
    lines.append("#pragma once")
    lines.append("")
    lines.append("#include <cstdint>")
    lines.append("")
    lines.append("namespace shim {")
    lines.append("namespace font {")
    lines.append("")
    lines.append("constexpr int kFirstChar = 0x%02X;" % FIRST)
    lines.append("constexpr int kLastChar  = 0x%02X;" % LAST)
    lines.append("constexpr int kGlyphCount = kLastChar - kFirstChar + 1;")
    lines.append("")
    lines.append("struct Glyph {")
    lines.append("    int16_t advance;   // pen movement, in pixels")
    lines.append("    int16_t width;     // bitmap width; zero for a blank")
    lines.append("    int16_t height;")
    lines.append("    int16_t top;       // rows below the line's top edge")
    lines.append("    uint32_t offset;   // into kBits")
    lines.append("};")
    lines.append("")
    lines.append("struct Face {")
    lines.append("    int16_t size;      // the pixel height it was asked for")
    lines.append("    int16_t ascent;")
    lines.append("    int16_t descent;")
    lines.append("    const Glyph * glyphs;")
    lines.append("};")
    lines.append("")

    lines.append("inline constexpr uint8_t kBits[] = {")
    for i in range(0, len(blob), 24):
        chunk = ", ".join("0x%02X" % b for b in blob[i:i + 24])
        lines.append("    %s," % chunk)
    lines.append("};")
    lines.append("")

    for size, ascent, descent, entries in faces:
        lines.append("inline constexpr Glyph kGlyphs%d[kGlyphCount] = {" % size)
        for advance, w, h, top, offset in entries:
            lines.append("    {%d, %d, %d, %d, %d}," % (advance, w, h, top, offset))
        lines.append("};")
        lines.append("")

    lines.append("inline constexpr Face kFaces[] = {")
    for size, ascent, descent, _ in faces:
        lines.append("    {%d, %d, %d, kGlyphs%d}," % (size, ascent, descent, size))
    lines.append("};")
    lines.append("constexpr int kFaceCount = %d;" % len(faces))
    lines.append("")
    lines.append("}   // namespace font")
    lines.append("}   // namespace shim")
    lines.append("")

    with open(args.output, "w", newline="\n") as out:
        out.write("\n".join(lines))

    print("%s: %d sizes, %d glyphs each, %d bytes of bitmap"
          % (args.output, len(faces), LAST - FIRST + 1, len(blob)))


if __name__ == "__main__":
    main()
